name: Generate Catalog PR

on: workflow_dispatch


jobs:
  check-for-deprecations:
    name: Check for Deprecated Messages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12
          token: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Install dependencies
        run: cd utils && yarn install

      - name: Validate files
        env:
          GIT_AUTHOR_NAME: "nr-opensource-bot"
          GIT_AUTHOR_EMAIL: "opensource+bot@newrelic.com"
          GIT_COMMITTER_NAME: "nr-opensource-bot"
          GIT_COMMITTER_EMAIL: "opensource+bot@newrelic.com"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NR_QUERY_KEY: ${{ secrets.NR_QUERY_KEY }}
          NR_ACCOUNT_ID: ${{ secrets.NR_ACCOUNT_ID }}
        run: cd utils && yarn check-for-deprecations

