name: Generate Catalog PR

on: workflow_dispatch
env:
  GIT_AUTHOR_NAME: "nr-opensource-bot"
  GIT_AUTHOR_EMAIL: "opensource+bot@newrelic.com"
  GIT_COMMITTER_NAME: "nr-opensource-bot"
  GIT_COMMITTER_EMAIL: "opensource+bot@newrelic.com"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  check-for-deprecations:
    name: Ensure schema compliance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12
  
      - name: Install dependencies
        run: cd utils && yarn install

      - name: Validate files
        run: cd utils && yarn check-for-deprecations

